services:
  applications-db:
    image: postgres:16
    container_name: applications-db
    environment:
      POSTGRES_DB: applications_db
      POSTGRES_USER: applications_user
      POSTGRES_PASSWORD: applications_pass
    ports:
      - "5432:5432"
    volumes:
      - applications_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  applications_pgdata:
